// ESM wrapper for Nearley-generated grammar
// The grammar.ts file is generated by Nearley and uses CommonJS,
// so we need to dynamically import it

let grammarModule: any = null;

export async function loadGrammar() {
  if (grammarModule) return grammarModule;

  // In Node.js
  if (typeof window === 'undefined') {
    const { createRequire } = await import('node:module');
    const require = createRequire(import.meta.url);
    grammarModule = require('./grammar.js');
    return grammarModule;
  }

  // In browser - the grammar file needs to be bundled
  // For now, throw an error with helpful message
  throw new Error(
    'Grammar loading in browser requires build-time bundling. ' +
    'Please ensure the grammar is properly bundled with your build tool.'
  );
}

// For synchronous usage when grammar is pre-loaded
export function getGrammar() {
  if (!grammarModule) {
    throw new Error('Grammar not loaded. Call loadGrammar() first.');
  }
  return grammarModule;
}
